// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAzVg0qC74XBGgQdpXnbKx504og2HwFwg',
    appId: '1:48929464388:web:07913bbcc8da11eb4ddc11',
    messagingSenderId: '48929464388',
    projectId: 'home-stock-app-db',
    authDomain: 'home-stock-app-db.firebaseapp.com',
    storageBucket: 'home-stock-app-db.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj-OINuFcwpk-bC5CuEDJfD5f_u5LPJxI',
    appId: '1:48929464388:android:669ad5eec3a2572c4ddc11',
    messagingSenderId: '48929464388',
    projectId: 'home-stock-app-db',
    storageBucket: 'home-stock-app-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5YrQjQay6g-ZR4DHaII2fnbKtdkfRqBs',
    appId: '1:48929464388:ios:17ad21b0c1f459e54ddc11',
    messagingSenderId: '48929464388',
    projectId: 'home-stock-app-db',
    storageBucket: 'home-stock-app-db.firebasestorage.app',
    iosBundleId: 'com.example.myhome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5YrQjQay6g-ZR4DHaII2fnbKtdkfRqBs',
    appId: '1:48929464388:ios:17ad21b0c1f459e54ddc11',
    messagingSenderId: '48929464388',
    projectId: 'home-stock-app-db',
    storageBucket: 'home-stock-app-db.firebasestorage.app',
    iosBundleId: 'com.example.myhome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC29ZkcOUMSOhqn5syBLLLj-yaMEsiaSFk',
    appId: '1:48929464388:web:178bbb8bbc28c88c4ddc11',
    messagingSenderId: '48929464388',
    projectId: 'home-stock-app-db',
    authDomain: 'home-stock-app-db.firebaseapp.com',
    storageBucket: 'home-stock-app-db.firebasestorage.app',
  );
}
